# Generated by Django 4.0 on 2022-01-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livepolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question_text',
        ),
    ]
